version: '3'
services:
  taskmanagerapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
      - '8001:443'
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    container_name: sql_server_container
    restart: always 
    environment:
      - SA_PASSWORD=mypwd2023
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
